#!/usr/bin/env bash
# Produces the vault-UI source package by driving Flap's own tooling. It does not build an archive.
#
# It used to. It copied our four source files next to three files lifted out of Flap's template and
# zipped the result, which produced something that looked like `yarn vault:package` output and was
# not. Flap's offline preflight rejected it on sight — `qa/e2e-report.json` is not merely a report,
# it is one of the files their intake checks for, and a package without it never reaches the
# Workbench at all:
#
#   "This ZIP was not generated by our official packaging tool, and its file structure does not
#    match a valid Flap Vault UI source package. Missing required package files: qa/e2e-report.json."
#
# The previous version of this script deleted that report deliberately, reasoning that shipping a
# report describing an earlier revision of the source was worse than shipping none. That reasoning
# was answering the wrong question. The choice was never "stale report or no report" — it was
# "regenerate the report", which only their tool can do, because only their tool runs the e2e that
# produces it. `vault-package.mjs` says so in its own output: "Submit this zip only; manually
# assembled zips without flap-vault-package.json should be rejected by the Flap Artifact Workbench."
#
# So the four files we own are copied INTO the template and their pipeline runs over them. Nothing
# here writes a zip, and nothing here touches one after their tool has.
set -euo pipefail
cd "$(dirname "$0")/.."

TEMPLATE="${FLAP_TEMPLATE:-$(cd .. && pwd)/flap-vault-component-template}"
[ -d "$TEMPLATE" ] || {
  echo "no Flap template at $TEMPLATE" >&2
  echo "  git clone https://github.com/flap-sh/flap-vault-component-template" >&2
  echo "  (or set FLAP_TEMPLATE to where it lives)" >&2
  exit 1
}

# The ABI slice is ours and is derived from vaultUISchema(); a stale slice is silent, so it is
# checked before anything is copied anywhere.
node tools/sync-flap-ui-abi.mjs --check

# The binding addresses, derived from deployments/*-latest.json rather than hand-maintained. This
# is the check that would have caught a manifest naming a factory three deployments old.
node tools/sync-ui-addresses.mjs --check || {
  echo "refusing to package: flap-ui bindings do not match deployments/*-latest.json" >&2
  exit 1
}

# Their freshness gate refuses to package against a template behind the published commit, and it is
# worth failing here with that message rather than midway through their pipeline.
( cd "$TEMPLATE" && node scripts/check-template-fresh.mjs >/dev/null ) || {
  echo "the Flap template is not up to date; git pull in $TEMPLATE" >&2
  exit 1
}

mkdir -p "$TEMPLATE/src/vaults/assay"
cp flap-ui/Component.tsx flap-ui/VaultABI.ts flap-ui/i18n.json flap-ui/manifest.json \
   "$TEMPLATE/src/vaults/assay/"

cd "$TEMPLATE"
node scripts/vault-register.mjs assay >/dev/null
node scripts/vault-check.mjs assay >/dev/null
node scripts/vault-e2e.mjs assay >/dev/null
node scripts/check-template-fresh.mjs --sync --quiet
node scripts/vault-package.mjs assay > /tmp/assay-vault-package.json
node scripts/vault-verify-package.mjs dist/assay.zip >/dev/null

SHA=$(node -e 'console.log(JSON.parse(require("fs").readFileSync("/tmp/assay-vault-package.json","utf8")).sha256)')
cd - >/dev/null

# Copied, never rebuilt. The sha256 their tool reported is re-checked on the copy, so the file the
# operator submits is provably the file their pipeline produced.
mkdir -p dist
cp "$TEMPLATE/dist/assay.zip" dist/assay.zip
GOT=$(shasum -a 256 dist/assay.zip | awk '{print $1}')
[ "$SHA" = "$GOT" ] || { echo "copy does not match what their tool produced: $SHA vs $GOT" >&2; exit 1; }

echo "dist/assay.zip — produced by $TEMPLATE, verified by their vault:verify-package"
echo "sha256 $GOT"
echo "submit this file unmodified"
