#!/usr/bin/env node
/**
 * Generates `src/abi.ts` from the Foundry build artifacts.
 *
 * A hand-written frontend ABI drifts from the contract the moment a signature changes, and the
 * drift is silent — calls just start reverting or decoding to nonsense. So the ABI is generated,
 * never authored, and `--check` fails the build when the committed copy no longer matches what
 * the contracts actually compile to.
 */
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const repo = resolve(here, "..", "..");
const outDir = resolve(repo, "out");
const target = resolve(here, "..", "src", "abi.ts");

const CONTRACTS = ["Tournament", "AgentRoster", "AssayToken", "AssayFlapVault"];

function loadAbi(name) {
  const path = resolve(outDir, `${name}.sol`, `${name}.json`);
  if (!existsSync(path)) {
    console.error(`missing artifact: ${path}\nrun \`forge build\` first`);
    process.exit(1);
  }
  return JSON.parse(readFileSync(path, "utf8")).abi;
}

const banner = `// GENERATED by scripts/sync-abi.mjs from the Foundry artifacts in ../out.
// Do not edit by hand — run \`npm run sync-abi\` after changing a contract.
`;

const body = CONTRACTS.map(
  (name) => `export const ${name.toLowerCase()}Abi = ${JSON.stringify(loadAbi(name), null, 2)} as const;\n`,
).join("\n");

const next = banner + "\n" + body;

if (process.argv.includes("--check")) {
  const current = existsSync(target) ? readFileSync(target, "utf8") : "";
  if (current !== next) {
    console.error(
      "src/abi.ts is out of date with the compiled contracts.\nrun `npm run sync-abi` and commit the result.",
    );
    process.exit(1);
  }
  console.log("abi in sync");
  process.exit(0);
}

writeFileSync(target, next);
console.log(`wrote ${target} (${CONTRACTS.join(", ")})`);
