#!/usr/bin/env node
/**
 * Generates `src/abi.ts` from the Foundry build artifacts.
 *
 * A hand-written frontend ABI drifts from the contract the moment a signature changes, and the
 * drift is silent — calls just start reverting or decoding to nonsense. So the ABI is generated,
 * never authored, and `--check` fails the build when the committed copy no longer matches what
 * the contracts actually compile to.
 */
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const repo = resolve(here, "..", "..");
const outDir = resolve(repo, "out");
const target = resolve(here, "..", "src", "abi.ts");

const CONTRACTS = ["Tournament", "AgentRoster", "AssayFlapVault"];

/**
 * The tax token is minted by Flap's portal, not by anything in this repository, so there is no
 * Foundry artifact to generate its ABI from. The frontend reads exactly two things off it, both
 * standard ERC-20 views, so this is the whole of what it needs — written out here rather than in
 * `src/abi.ts` because that file is generated and a hand-edit there is erased by the next sync.
 */
const HAND_WRITTEN = {
  assaytoken: [
    { type: "function", name: "totalSupply", inputs: [], outputs: [{ type: "uint256" }], stateMutability: "view" },
    { type: "function", name: "symbol", inputs: [], outputs: [{ type: "string" }], stateMutability: "view" },
  ],
};

function loadAbi(name) {
  const path = resolve(outDir, `${name}.sol`, `${name}.json`);
  if (!existsSync(path)) {
    console.error(`missing artifact: ${path}\nrun \`forge build\` first`);
    process.exit(1);
  }
  return JSON.parse(readFileSync(path, "utf8")).abi;
}

const banner = `// GENERATED by scripts/sync-abi.mjs from the Foundry artifacts in ../out.
// Do not edit by hand — run \`npm run sync-abi\` after changing a contract.
`;

const generated = CONTRACTS.map(
  (name) => `export const ${name.toLowerCase()}Abi = ${JSON.stringify(loadAbi(name), null, 2)} as const;\n`,
);
const handWritten = Object.entries(HAND_WRITTEN).map(
  ([name, abi]) => `export const ${name}Abi = ${JSON.stringify(abi, null, 2)} as const;\n`,
);
const body = [...generated, ...handWritten].join("\n");

const next = banner + "\n" + body;

/**
 * Every `*Abi` this file will export. Checked against what the app actually imports, because
 * matching our own output against our own output proves nothing about the consumer: `chain.ts`
 * imported `assaytokenAbi` for months while this said "abi in sync", and the missing export only
 * surfaced in `vite build` — which never ran, because an earlier step in `npm run verify` always
 * failed first. A gate that only reads its own homework is how that survives.
 */
const exported = new Set([...CONTRACTS.map((n) => n.toLowerCase()), ...Object.keys(HAND_WRITTEN)]);

function checkConsumers() {
  const consumers = ["src/chain.ts"];
  let bad = 0;
  for (const rel of consumers) {
    const path = resolve(here, "..", rel);
    if (!existsSync(path)) continue;
    const src = readFileSync(path, "utf8");
    for (const m of src.matchAll(/import\s*\{([^}]*)\}\s*from\s*"\.\/abi"/g)) {
      for (const raw of m[1].split(",")) {
        const name = raw.trim().replace(/^type\s+/, "");
        if (!name) continue;
        const base = name.replace(/Abi$/, "");
        if (!exported.has(base)) {
          console.error(`${rel} imports ${name}, which src/abi.ts does not export`);
          bad++;
        }
      }
    }
  }
  return bad;
}

if (process.argv.includes("--check")) {
  const current = existsSync(target) ? readFileSync(target, "utf8") : "";
  if (current !== next) {
    console.error(
      "src/abi.ts is out of date with the compiled contracts.\nrun `npm run sync-abi` and commit the result.",
    );
    process.exit(1);
  }
  if (checkConsumers() > 0) process.exit(1);
  console.log("abi in sync");
  process.exit(0);
}

writeFileSync(target, next);
console.log(`wrote ${target} (${CONTRACTS.join(", ")})`);
